### PR TITLE
Create ViewsBlockAreaManager class to remove dependency from drupal/b…

### PR DESCRIPTION
**Pull request by Coufu**
I copied over the code from BlockFieldManager to work for this module. Tested on my project and looks like it's good to go.

### CODE REVIEW

**Comment by leonk** [comment]
Thanks for the PR!

Just taking a look at this, I'm not sure if it's worth having a service that just collects block definitions.  It wouldn't be that much work to do it inside the Views area plugin itself, and result in a lot less code.
I know that block_field does that, but it uses this service from more than one place so it makes sense to share the functionality in a service.  Whereas for this module, I can't see that ever happening.

**Comment by Coufu** [comment]
Yeah I was trying to figure out a better way to handle this, like if I could just contain the functions in the class itself, but I couldn’t find out how to do that without creating the service. I was also trying to finish up a task at work, so I just took the path of least resistance for it to work.

Anyway, let me know once you find a better solution. Looking forward to it :) 

Doug

**Comment by leonk** [comment]
Sorry for the delayed response, and finally got round to working on this.  Have opened a new PR which injects the block manager service directly into the plugin (no need for another service).
PR: https://github.com/leonk/views_block_area/pull/2

@Coufu there is some documentation on it here in case you're interested: https://www.lullabot.com/articles/injecting-services-in-your-d8-plugins

**Comment by Coufu** [comment]
Awesome! Great work. Thanks for the link. 

Doug

**Pull request closed without merging**
